#!/bin/bash
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=16
#PBS -q serial
#PBS -N Matlab
#PBS -o out.$PBS_JOBNAME.$PBS_JOBID
#PBS -e err.$PBS_JOBNAME.$PBS_JOBID


cd $PBS_O_WORKDIR


matlab -nodesktop -r fft_test

